ci: enable releasing Ferron 2.x beta Docker images

diff --git a/.github/workflows/release-v2.yml b/.github/workflows/release-v2.yml
--- a/.github/workflows/release-v2.yml
+++ b/.github/workflows/release-v2.yml
@@ -220,91 +220,91 @@ jobs:
   #         # The "deploy-ferron2-rustdocs" is a custom command that deploys the Ferron's Rust crate documentation
   #         ssh ferron-servers "sudo deploy-ferron2-rustdocs ferron2-rustdocs.zip && rm ferron2-rustdocs.zip"
 
-  # docker:
-  #   runs-on: ubuntu-latest
+  docker:
+    runs-on: ubuntu-latest
 
-  #   permissions:
-  #     packages: write
-  #     contents: read
-  #     attestations: write
-  #     id-token: write
+    permissions:
+      packages: write
+      contents: read
+      attestations: write
+      id-token: write
 
-  #   strategy:
-  #     fail-fast: false
-  #     matrix:
-  #       include:
-  #         - group: latest
-  #           dockerfile: ./Dockerfile
-  #         - group: alpine
-  #           dockerfile: ./Dockerfile.alpine
+    strategy:
+      fail-fast: false
+      matrix:
+        include:
+          - group: latest
+            dockerfile: ./Dockerfile
+          - group: alpine
+            dockerfile: ./Dockerfile.alpine
 
-  #   steps:
-  #     - name: Checkout
-  #       uses: actions/checkout@v4
-  #       with:
-  #         ref: main
-  #         fetch-depth: 0
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          ref: main
+          fetch-depth: 0
 
-  #     - name: Log in to Docker Hub
-  #       uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
-  #       with:
-  #         username: ${{ secrets.DOCKER_USERNAME }}
-  #         password: ${{ secrets.DOCKER_PASSWORD }}
+      - name: Log in to Docker Hub
+        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
 
-  #     - name: Log in to GitHub Container Registry
-  #       uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
-  #       with:
-  #         registry: ghcr.io
-  #         username: ${{ github.actor }}
-  #         password: ${{ secrets.GITHUB_TOKEN }}
+      - name: Log in to GitHub Container Registry
+        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
 
-  #     - name: Determine Ferron version
-  #       shell: bash
-  #       run: |
-  #         FERRON_VERSION_CARGO="$(cat ferron/Cargo.toml | grep -E '^version' | sed -E 's|.*"([0-9a-zA-Z.+-]+)"$|\1|g')"
-  #         FERRON_VERSION_GIT="$(git tag --sort=-committerdate | head -n 1 | sed s/[^0-9a-zA-Z.+-]//g)"
-  #         if [ "$FERRON_VERSION_CARGO" != "" ]; then
-  #           echo "Version determined from Cargo.toml file"
-  #           echo "FERRON_VERSION=$FERRON_VERSION_CARGO" >> $GITHUB_ENV
-  #         elif  [ "$FERRON_VERSION_GIT" != "" ]; then
-  #           echo "Version determined from the Git tag"
-  #           echo "FERRON_VERSION=$FERRON_VERSION_GIT" >> $GITHUB_ENV
-  #         else
-  #           echo "Can't determine the server version!" 2>&1
-  #           exit 1
-  #         fi
+      - name: Determine Ferron version
+        shell: bash
+        run: |
+          FERRON_VERSION_CARGO="$(cat ferron/Cargo.toml | grep -E '^version' | sed -E 's|.*"([0-9a-zA-Z.+-]+)"$|\1|g')"
+          FERRON_VERSION_GIT="$(git tag --sort=-committerdate | head -n 1 | sed s/[^0-9a-zA-Z.+-]//g)"
+          if [ "$FERRON_VERSION_CARGO" != "" ]; then
+            echo "Version determined from Cargo.toml file"
+            echo "FERRON_VERSION=$FERRON_VERSION_CARGO" >> $GITHUB_ENV
+          elif  [ "$FERRON_VERSION_GIT" != "" ]; then
+            echo "Version determined from the Git tag"
+            echo "FERRON_VERSION=$FERRON_VERSION_GIT" >> $GITHUB_ENV
+          else
+            echo "Can't determine the server version!" 2>&1
+            exit 1
+          fi
 
-  #     - name: Determine Docker tags
-  #       shell: bash
-  #       run: |
-  #         TAG_TYPE=${{ matrix.group }}
-  #         FERRON_MAJOR_VERSION=$(echo "$FERRON_VERSION" | cut -d '.' -f 1)
-  #         if [ "$TAG_TYPE" = "latest" ] || [ "$TAG_TYPE" = "" ]; then
-  #           DOCKER_HUB_TAGS="ferronserver/ferron:$FERRON_VERSION,ferronserver/ferron:$FERRON_MAJOR_VERSION,ferronserver/ferron:latest"
-  #           DOCKER_GHCR_TAGS="ghcr.io/ferronweb/ferron:$FERRON_VERSION,ghcr.io/ferronweb/ferron:$FERRON_MAJOR_VERSION,ghcr.io/ferronweb/ferron:latest"
-  #         else
-  #           DOCKER_HUB_TAGS="ferronserver/ferron:$FERRON_VERSION-$TAG_TYPE,ferronserver/ferron:$FERRON_MAJOR_VERSION-$TAG_TYPE,ferronserver/ferron:$TAG_TYPE"
-  #           DOCKER_GHCR_TAGS="ghcr.io/ferronweb/ferron:$FERRON_VERSION-$TAG_TYPE,ghcr.io/ferronweb/ferron:$FERRON_MAJOR_VERSION-$TAG_TYPE,ghcr.io/ferronweb/ferron:TAG_TYPE"
-  #         fi
-  #         echo "DOCKER_TAGS=$DOCKER_HUB_TAGS,$DOCKER_GHCR_TAGS" >> $GITHUB_ENV
+      - name: Determine Docker tags
+        shell: bash
+        run: |
+          TAG_TYPE=${{ matrix.group }}
+          FERRON_MAJOR_VERSION=$(echo "$FERRON_VERSION" | cut -d '.' -f 1)
+          if [ "$TAG_TYPE" = "latest" ] || [ "$TAG_TYPE" = "" ]; then
+            DOCKER_HUB_TAGS="ferronserver/ferron:$FERRON_VERSION,ferronserver/ferron:$FERRON_MAJOR_VERSION"
+            DOCKER_GHCR_TAGS="ghcr.io/ferronweb/ferron:$FERRON_VERSION,ghcr.io/ferronweb/ferron:$FERRON_MAJOR_VERSION"
+          else
+            DOCKER_HUB_TAGS="ferronserver/ferron:$FERRON_VERSION-$TAG_TYPE,ferronserver/ferron:$FERRON_MAJOR_VERSION-$TAG_TYPE"
+            DOCKER_GHCR_TAGS="ghcr.io/ferronweb/ferron:$FERRON_VERSION-$TAG_TYPE,ghcr.io/ferronweb/ferron:$FERRON_MAJOR_VERSION-$TAG_TYPE"
+          fi
+          echo "DOCKER_TAGS=$DOCKER_HUB_TAGS,$DOCKER_GHCR_TAGS" >> $GITHUB_ENV
 
-  #     - name: Set up Docker Buildx
-  #       uses: docker/setup-buildx-action@v3
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
 
-  #     - name: Build and push Docker image
-  #       id: push
-  #       uses: docker/build-push-action@1dc73863535b631f98b2378be8619f83b136f4a0
-  #       with:
-  #         context: .
-  #         file: ${{ matrix.dockerfile }}
-  #         push: true
-  #         tags: ${{ env.DOCKER_TAGS }}
-  #         cache-from: type=gha
-  #         cache-to: type=gha,mode=max
+      - name: Build and push Docker image
+        id: push
+        uses: docker/build-push-action@1dc73863535b631f98b2378be8619f83b136f4a0
+        with:
+          context: .
+          file: ${{ matrix.dockerfile }}
+          push: true
+          tags: ${{ env.DOCKER_TAGS }}
+          cache-from: type=gha
+          cache-to: type=gha,mode=max
 
-  #     - name: Generate artifact attestation
-  #       uses: actions/attest-build-provenance@v2
-  #       with:
-  #         subject-name: index.docker.io/ferronserver/ferron
-  #         subject-digest: ${{ steps.push.outputs.digest }}
-  #         push-to-registry: true
+      - name: Generate artifact attestation
+        uses: actions/attest-build-provenance@v2
+        with:
+          subject-name: index.docker.io/ferronserver/ferron
+          subject-digest: ${{ steps.push.outputs.digest }}
+          push-to-registry: true
